version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-tutorial-02"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1jmp2lj5bf5hg"
s3_prefix = "sam-tutorial-02"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
